apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
- namespace.yaml
- postgres.yaml

helmCharts:
  - name: mealie
    repo: https://jslancaster.github.io/helm-charts
    version: 0.1.0
    releaseName: mealie
    namespace: mealie
    valuesFile: values.yaml