# config:
#   database:
#     engine: postgres
#     postgres:
#       existingSecret: cluster-example-app
#       existingSecretHostKey: host
#       existingSecretPortKey: port
#       existingSecretDatabaseKey: dbname
#       existingSecretUsernameKey: username
#       existingSecretPasswordKey: password