config:
  database:
    engine: postgres
    postgres:
      existingSecret: mealie-app
      existingSecretHostKey: host
      existingSecretPortKey: port
      existingSecretDatabaseKey: dbname
      existingSecretUsernameKey: username
      existingSecretPasswordKey: password